"""
Export the titles + descriptions of all PUBLISHED videos on the channel to a
markdown file (.notes/published_videos.md).

Use this MD as context when generating new concepts so topics don't overlap.
Re-run anytime to refresh (e.g. after the scheduler uploads more).

Note: uses the YouTube Data API key, so it sees PUBLIC videos. Private/unlisted
videos won't appear (test uploads, etc.).

Usage:
    venv\\Scripts\\python.exe export_published.py            # @carakerja1
    venv\\Scripts\\python.exe export_published.py otherhandle
"""

import os
import sys

import requests
from loguru import logger

from app.config import config
from app.utils import utils

OUT_FILE = os.path.join(utils.root_dir(), ".notes", "published_videos.md")
API = "https://www.googleapis.com/youtube/v3"


def _key():
    keys = config.app.get("youtube_api_keys")
    if not keys:
        raise ValueError("youtube_api_keys not set in config.toml")
    return keys[0] if isinstance(keys, list) else keys


def get_uploads_playlist(handle: str, key: str) -> str:
    r = requests.get(
        f"{API}/channels?part=contentDetails,snippet&forHandle={handle}&key={key}",
        timeout=30,
    ).json()
    items = r.get("items", [])
    if not items:
        raise RuntimeError(f"channel @{handle} not found: {str(r)[:200]}")
    logger.info(f"channel: {items[0]['snippet']['title']}")
    return items[0]["contentDetails"]["relatedPlaylists"]["uploads"]


def list_video_ids(playlist_id: str, key: str) -> list:
    ids, page = [], ""
    while True:
        url = (
            f"{API}/playlistItems?part=contentDetails&maxResults=50"
            f"&playlistId={playlist_id}&key={key}"
        )
        if page:
            url += f"&pageToken={page}"
        r = requests.get(url, timeout=30).json()
        ids += [it["contentDetails"]["videoId"] for it in r.get("items", [])]
        page = r.get("nextPageToken", "")
        if not page:
            break
    return ids


def fetch_details(video_ids: list, key: str) -> list:
    out = []
    for i in range(0, len(video_ids), 50):
        batch = ",".join(video_ids[i : i + 50])
        r = requests.get(
            f"{API}/videos?part=snippet&id={batch}&key={key}", timeout=30
        ).json()
        for it in r.get("items", []):
            sn = it["snippet"]
            out.append(
                {
                    "id": it["id"],
                    "title": sn.get("title", ""),
                    "description": sn.get("description", ""),
                    "published": sn.get("publishedAt", ""),
                    "tags": sn.get("tags", []),
                }
            )
    return out


def main():
    handle = sys.argv[1] if len(sys.argv) > 1 else "carakerja1"
    key = _key()
    uploads = get_uploads_playlist(handle, key)
    ids = list_video_ids(uploads, key)
    videos = fetch_details(ids, key)
    videos.sort(key=lambda v: v.get("published", ""))
    logger.info(f"found {len(videos)} published video(s)")

    lines = [
        f"# Published videos — @{handle}",
        "",
        "Auto-generated by `export_published.py`. Use this as context when "
        "creating new concepts so topics DON'T overlap with what's already live.",
        "",
        "## Topics already covered",
    ]
    for v in videos:
        lines.append(f"- {v['title']}")
    lines.append("")
    lines.append("## Full details")
    lines.append("")
    for v in videos:
        lines.append(f"### {v['title']}")
        lines.append(f"- **URL:** https://youtu.be/{v['id']}")
        if v["published"]:
            lines.append(f"- **Published:** {v['published']}")
        if v["tags"]:
            lines.append(f"- **Tags:** {', '.join(v['tags'])}")
        lines.append("")
        lines.append(v["description"] or "_(no description)_")
        lines.append("")

    os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    logger.success(f"wrote {OUT_FILE} ({len(videos)} videos)")


if __name__ == "__main__":
    main()
